[project]
name = "image-processing-w4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keras==2.15.0",
    "keras-facenet>=0.3.2",
    "matplotlib>=3.11.1",
    "numpy==1.26.4",
    "opencv-python==4.10.0.84",
    "openpyxl>=3.1.5",
    "scikit-learn>=1.9.0",
    "tensorflow==2.15.1",
]
